---
- name: Validate sshd configuration
  ansible.builtin.command:
    cmd: sshd -t
  changed_when: false
  listen: Restart sshd

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  listen: Restart sshd
