---
- name: Set system timezone
  ansible.builtin.timezone:
    name: "{{ common_timezone }}"

- name: Install common packages
  ansible.builtin.dnf:
    name: "{{ common_packages }}"
    state: present
    disablerepo:
      - "alt-common*"
      - "imunify360-rollout-*"

- name: Ensure chronyd is enabled and running
  ansible.builtin.systemd:
    name: chronyd
    enabled: true
    state: started
